---
deployment:
  targets:
    - deployment_target: "amdakostrategies.com.ng"
      repository_root: "/"
      working_directory: "/"
      build_command: "/bin/bash build.sh"
      test_command: "test -f dist/index.html && test -f server.js"
      restart_reload_command: "/bin/bash restart.sh"
      environment_variables:
        - NODE_ENV=production
hooks:
  build:
    - export PATH=$PATH:/usr/local/bin
    - npm install --production
    - npm run build
  post_deployment:
    - npm install -g pm2
    - pm2 start server.js --name "amdako-api" || pm2 restart amdako-api
    - pm2 save
