// Database type for TypeScript typings
// This is generated by supabase based on your schema
// For now, we'll define basic types that match our schema
export type Database = {
  public: {
    Tables: {
      profiles: {
        Row: {
          id: string;
          full_name: string;
          first_name: string | null;
          last_name: string | null;
          email: string | null;
          phone: string;
          role: "user" | "admin";
          is_active: boolean;
          last_login: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id: string;
          full_name: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone: string;
          role?: "user" | "admin";
          is_active?: boolean;
          last_login?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          full_name?: string;
          first_name?: string;
          last_name?: string;
          email?: string;
          phone?: string;
          role?: "user" | "admin";
          is_active?: boolean;
          last_login?: string;
          updated_at?: string;
        };
      };
      agreements: {
        Row: {
          id: string;
          user_id: string;
          full_name: string;
          address: string | null;
          phone: string;
          email: string;
          id_type: "nationalId" | "votersCard" | "internationalPassport" | "driversLicense" | null;
          id_number: string | null;
          investment_amount: number;
          start_date: string;
          maturity_date: string | null;
          payment_method: string;
          payment_bank_name: string | null;
          payment_account_name: string | null;
          transaction_reference: string | null;
          returns_bank_name: string | null;
          returns_account_number: string | null;
          returns_account_name: string | null;
          returns_phone_number: string | null;
          signature_url: string | null;
          status: "pending" | "approved" | "rejected";
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          full_name: string;
          address?: string;
          phone: string;
          email: string;
          id_type?: "nationalId" | "votersCard" | "internationalPassport" | "driversLicense";
          id_number?: string;
          investment_amount: number;
          start_date: string;
          maturity_date?: string;
          payment_method?: string;
          payment_bank_name?: string;
          payment_account_name?: string;
          transaction_reference?: string;
          returns_bank_name?: string;
          returns_account_number?: string;
          returns_account_name?: string;
          returns_phone_number?: string;
          signature_url?: string;
          status?: "pending" | "approved" | "rejected";
        };
        Update: {
          full_name?: string;
          address?: string;
          phone?: string;
          email?: string;
          id_type?: "nationalId" | "votersCard" | "internationalPassport" | "driversLicense";
          id_number?: string;
          investment_amount?: number;
          start_date?: string;
          maturity_date?: string;
          payment_method?: string;
          payment_bank_name?: string;
          payment_account_name?: string;
          transaction_reference?: string;
          returns_bank_name?: string;
          returns_account_number?: string;
          returns_account_name?: string;
          returns_phone_number?: string;
          signature_url?: string;
          status?: "pending" | "approved" | "rejected";
        };
      };
      dashboard_metrics: {
        Row: {
          id: string;
          user_id: string | null;
          performance: string | null;
          balance: string | null;
          open_positions: number;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id?: string;
          performance?: string;
          balance?: string;
          open_positions?: number;
        };
        Update: {
          performance?: string;
          balance?: string;
          open_positions?: number;
        };
      };
      records: {
        Row: {
          id: string;
          user_id: string;
          title: string;
          content: string | null;
          type: string | null;
          amount: number | null;
          date: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          title: string;
          content?: string;
          type?: string;
          amount?: number;
          date?: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          title?: string;
          content?: string;
          type?: string;
          amount?: number;
          date?: string;
          updated_at?: string;
        };
      };
      products: {
        Row: {
          id: string;
          name: string;
          description: string | null;
          category: string | null;
          price: number | null;
          image: string | null;
          roi: string | null;
          min_investment: number | null;
          is_active: boolean;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          description?: string;
          category?: string;
          price?: number;
          image?: string;
          roi?: string;
          min_investment?: number;
          is_active?: boolean;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          name?: string;
          description?: string;
          category?: string;
          price?: number;
          image?: string;
          roi?: string;
          min_investment?: number;
          is_active?: boolean;
          updated_at?: string;
        };
      };
    };
    Views: {};
    Functions: {
      has_role: {
        Args: {
          role_name: string;
        };
        Returns: boolean;
      };
    };
    Storage: {
      Buckets: {
        agreements: {
          id: string;
          name: string;
          owner: string;
          public: boolean;
          file_size_limit: number;
          allowed_mime_types: string[];
        };
      };
    };
  };
};
